### ISSUE TITLE
shinyEvents in client\server shiny app

### ISSUE THREAD

**Issue by trufanov-nok** [skranz/shinyEvents#1]
Hi,
I wonder if it could be used for client\server apps. I mean ui.R\server.R approach. Currently all samples are in one R file and seems to share environment. I've tried to  do something like:

```
ui.R
-----
library(shinyEvents)

app = eventsApp()
app$verbose = T
app$ui = fluidPage(
 titlePanel("Word completion test app"),
  fluidRow(actionButton("dynBtn0", "starts[i]")) 
)

server.R
-----
shinyServer(function(input, output, session) {
buttonHandler("dynBtn0", function(session, value, ...) {warning("df");})   
})
```

And run it with RStudio's run button.

buttonHandler is invoked but when you press a button - nothing happens.
I suspect this is because `getApp()$session.env` is NULL in `addEventHandlerToApp()`

Could shinyEvents be used in that way? If so, could you give a short sample?

**Comment by skranz** [comment]
I updated the vignette (which is now also the README.md). The last section explains how ui.r, server.r and global.r should look like. The key idea is to put most code in global.r so that it is available in ui.r and server.r.

**Comment by trufanov-nok** [comment]
Great, thanks. Will take a look tomorrow.

**Comment by trufanov-nok** [comment]
Hello again,
Could you put installation notes into readme file? Right now it's self referencing, Just add there
`devtools::install_github(repo="skranz/shinyEvents")`
I've run into trouble bcs used `devtools::install_git(...)` instead - such configuration apparently can't be deployed to shinyapps.io cloud although it works locally.

As for vignette - it doesn't work for me before I made a few modifications which I want to suggest. 
At the beginning I made a few mistakes bcs I didn't realise that `app$server` is initialised inside `eventsApp()`. I tried to assign the function which was originally passed to `shinyServer()` to `app$server` manually and nothing worked as `app$is.running` was never changed to `TRUE`.

Then I tried to pass this function to `appInitHandler()` and it didn't work till I changed function declaration to `function(input, output, session, app). It could be`function(input, output, ...)`too. The problem is RStudio generates a server.R template with`shinyServer(function(input, output) { })` by default.

Last nuance - the changes you make in global.R won't be reflected in your app if you just press "Reload App" button in RStudio. I have to close my app and press "Run app" instead. Looks like RStudio doesn't track changes in files other than ui.R and server.R. That's RStudio problem - I'll send this to them as a bug.

Finally I made what I want. I'm currently passing one of coursera's trainings for fun and faced with a task to make a simple version of text input with word completion like in mobile phones. In shiny. So I was looking for a convenient way to create arbitrary number of buttons at run time and assign own event handler to each of them. The resulting shiny app template (assuming one-liners in server and ui R files) is following:

```
# global.R
library(shinyEvents)

# Predicative text input template

app = eventsApp()

app$ui = fluidPage(    
  titlePanel("Text input with word completion"),
  fluidRow(
    textInput(inputId = "txt", label = "Please type in your text message:", value = ""),
    uiOutput("ui")    
  )
)

# dummy data
words <- c("word 1", "word 2", "word 3", "word 4", "word 5")

create_buttons <- function(input, output, session, words)
{
  dynUI <- list()
  if (!is.null(words))
    for (i in 1:length(words))
    {
      id <- paste0("dynBtn",i)
      word <- words[i]
      dynUI <- list(dynUI, actionButton(id, word) )  

      buttonHandler( id, word = word, function(session, value, word, ...) 
      {
        s <- input$txt
        if (nchar(s) == 0) s <- word
        else s <- paste(s, word)
        updateTextInput(session, "txt", value = s)
      })    
    }
  output$ui <- renderUI({dynUI})
}

appInitHandler(function(input, output, session, ...) {

  create_buttons(input, output, session, words)

  observe({

    str <- input$txt 
    if (nchar(str) <= 0) return();

    # new buttons may be created here
    # based on prediction model for str
    # as a demo - just decreasing btn number
    if (length(words) > 1)
      words <<- words[1:(length(words)-1)]
    else words <<- NULL
    create_buttons(input, output, session, words)
  })

})
```

**Comment by skranz** [comment]
Thanks for the feedback. I updated the vignette correspondingly.

**Comment by trufanov-nok** [comment]
Hi Sebastian, you may close this issue.
